export const SAVE_VIDEO = 'SAVE_VIDEO';
export const UPDATE_COORDINATS = 'UPDATE_COORDINATS';
export const START_RECORDING = 'START_RECORDING';
export const STOP_RECORDING = 'STOP_RECORDING';
export const CHANGE_CAMERA_TYPE = 'CHANGE_CAMERA_TYPE';
export const CHANGE_FLASH_MODE = 'CHANGE__FLASH_MODE';

