export const SAVE_VIDEO = 'SAVE_VIDEO';
export const UPDATE_COORDINATS = 'UPDATE_COORDINATS';
export const START_RECORDING = 'START_RECORDING';
export const STOP_RECORDING = 'STOP_RECORDING';
export const CHANGE_CAMERA_TYPE = 'CHANGE_CAMERA_TYPE';
export const CHANGE_FLASH_MODE = 'CHANGE__FLASH_MODE';
export const INCREASE_RECORDING_TIME = 'INCREASE_RECORDING_TIME';
export const CLEAR_RECORDING_TIME = 'CLEAR_RECORDING_TIME';
export const CHANGE_CAMERA_VISIBILITY_FLAG = 'CHANGE_CAMERA_VISIBILITY_FLAG';
export const SWITCH_CAMERA_AR_OR_VIDEO = 'SWITCH_CAMERA_AR_OR_VIDEO';
export const SET_CURRENT_VIDEO = 'SET_CURRENT_VIDEO';
export const UPDATE_VIDEO_LIST = 'UPDATE_VIDEO_LIST';
export const SET_VIDEO_TITLE = 'SET_VIDEO_TITLE';
export const POP_NEEDED = 'POP_NEEDED';


export const MODE_SUBMIT = 'MODE_SUBMIT';
export const MODE_WATCH = 'MODE_WATCH';

export const VIDEO = 'VIDEO';
export const AR = 'AR';
